## Numpy Tutorial

1. 创建数组
2. 数组运算
3. 数学函数
4. 数组切片和索引
5. 数组形状操作
6. 数组排序
7. 数组统计

In [205]:
import numpy as np
np.zeros
np.ones
np.arange
np.reshape
np.eye
np.diag
np.linspace
np.random.rand
np.random.random
np.random.randn
np.random.randint
np.random.normal
from functools import reduce
np.fromfunction(lambda i, j, k: i + j + k, (3, 3, 3))
A = np.array([[1, 2, 3], [2, 3, 4]])
B = np.array([[3, 2], [3, 4], [1, 3]])
np.dot(A, B)
np.mat(A) * np.mat(B)
A.T
# inverse
np.linalg.inv(A[:,:2])
np.sin
np.exp
np.sqrt
np.power(A, 2)
# slice

A.resize(3, 2) # change A
A.ravel()

# merge
# vertical
np.vstack((A, A))
# horizon
np.hstack((A, A))
# concatenate
Z1 = np.arange(3)
Z2 = np.arange(3,7)
Z3 = np.arange(7,10)
Z = np.array([Z1, Z2, Z3])
print(Z)
np.concatenate(Z)
# c_, r_
M1 = np.array([1, 2, 3])
M2 = np.array([4, 5, 6])
np.c_[M1, M2] # column
np.r_[M1, M2] # row

# split
np.hsplit(A, 2)
np.vsplit(A, 3)

# max min
np.max(A, axis = 0)
np.max(A, axis = 1)
np.min(A, axis = 0)
np.min(A, axis = 1)

# argmax argmin
np.argmax(A, axis = 0)
np.argmax(A, axis = 1)
np.argmin(A, axis = 0)
np.argmin(A, axis = 1)
# array.argmax()

# statistics
np.median
np.mean
np.average # arg: weights
np.var
np.std

# conditional index
A[A>3]
A[A<5]
A = np.array([np.random.rand(10) for i in range(5)])
print(A)
print(A[[0,0,0], [1,2,3]])

# intersect
A = np.array([1,2,3])
B = np.array([1,4,5])
np.intersect1d(A, B)

# date
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("yesterday: ", yesterday)
print("today: ", today)
print("tomorrow: ", tomorrow)

# transform to int: ceil floor int
np.ceil
np.floor
A.astype(int)
np.trunc # = floor

# sort
A.sort()
# sort by the thrid col
Z = np.random.randint(0,10,(5,5))
print("before sort：\n",Z)
Z[Z[:,2].argsort()]

# bincount
A = np.random.randint(0, 10, 50)
np.bincount(A)

# nonzero
np.nonzero(A)

# np.put, np.random.choice
p = 3
Z = np.zeros((5,5))
np.put(Z, np.random.choice(range(5*5), p, replace = False), 1)

# np.einsum https://zhuanlan.zhihu.com/p/27739282

# np.argsort()
# return index of biggest to smallest
np.argsort(A, axis = 0) # col

# set precision
A = np.random.rand(10)
np.set_printoptions(precision=4)
print(A)
print(A/1e4)

# quantile
np.percentile(A, q = [10, 50, 80])

# np.isnan, np.where
A = np.array([np.random.rand(10) for i in range(5)])
A[np.random.randint(0,5,4), np.random.randint(0,5,4)] = np.nan
# judge wether nan exist
np.isnan(A)
# find index of nan
np.where(np.isnan(A))
# drop nan value based on row
print(A)
print(A[np.sum(np.isnan(A), axis=1) == 0])
print(A.T[np.sum(np.isnan(A), axis=0) == 0])

# np.unique
a = np.array([[1, 0, 0], [1, 0, 0], [2, 3, 4]])
np.unique(a, axis=0)

# distance Euler
a = np.array([2,3,4])
b = np.array([1,2,3])
np.linalg.norm(b-a, 2)

# correlation matrix
A = np.nan_to_num(A)
np.corrcoef(A)

# eignvalue and eignvector
M = np.matrix([[1,2,3], [4,5,6], [7,8,9]])
w, v = np.linalg.eig(M)

# diff
np.diff(A)

# cum sum
np.cumsum(A)

[array([0, 1, 2]) array([3, 4, 5, 6]) array([7, 8, 9])]
[[0.364  0.0251 0.5414 0.06   0.1553 0.7599 0.2215 0.9515 0.2879 0.6773]
 [0.4419 0.2782 0.9332 0.0323 0.652  0.9511 0.759  0.8014 0.6579 0.5491]
 [0.9064 0.1106 0.973  0.1086 0.2206 0.2802 0.2303 0.1638 0.407  0.3743]
 [0.1703 0.5749 0.7347 0.2911 0.166  0.2953 0.3527 0.1278 0.6376 0.034 ]
 [0.9516 0.7934 0.244  0.6881 0.3647 0.594  0.6791 0.0784 0.9662 0.5513]]
[0.0251 0.5414 0.06  ]
yesterday:  2018-08-26
today:  2018-08-27
tomorrow:  2018-08-28
before sort：
 [[7 6 7 7 2]
 [9 3 3 0 8]
 [3 9 2 8 3]
 [5 3 9 2 8]
 [2 3 0 0 8]]
[0.0715 0.3376 0.0286 0.4908 0.99   0.002  0.6543 0.3455 0.0625 0.883 ]
[7.1453e-06 3.3760e-05 2.8621e-06 4.9083e-05 9.9001e-05 2.0474e-07
 6.5426e-05 3.4545e-05 6.2475e-06 8.8300e-05]
[[0.6013 0.4439    nan 0.2578 0.566  0.5467 0.0393 0.2128 0.5015 0.9067]
 [0.8398 0.5772 0.8895 0.8498    nan 0.1518 0.0357 0.0145 0.7202 0.0795]
 [0.4785 0.8573 0.9226 0.928     nan 0.2388 0.6782 0.6204 0.3521 0.7929]
 [0.291

array([ 0.6013,  1.0452,  1.0452,  1.303 ,  1.869 ,  2.4156,  2.4549,
        2.6677,  3.1692,  4.0759,  4.9157,  5.4929,  6.3823,  7.2321,
        7.2321,  7.3839,  7.4196,  7.4341,  8.1543,  8.2338,  8.7123,
        9.5696, 10.4922, 11.4202, 11.4202, 11.659 , 12.3371, 12.9576,
       13.3097, 14.1026, 14.394 , 14.8973, 15.451 , 15.8905, 16.6584,
       17.4566, 17.5249, 18.0075, 18.9897, 19.0617, 19.3634, 19.4326,
       20.1254, 20.1254, 20.394 , 21.0467, 21.1053, 21.6519, 21.7043,
       21.8201])