### Some Questions
* ? Zip 转置 tuple(zip(*data))  
* ? 列表元素差异, 列表元素差异下标
* ? L1=[1,2,3,4,5], L2=["star","moon"], L3=[1,2,"star"]，输出最长的列表。

* Q1

In [104]:
import numpy as np
a = np.array([[0,1,2], [1,2,3]])
print(a)
print(a.T)

[[0 1 2]
 [1 2 3]]
[[0 1]
 [1 2]
 [2 3]]


In [107]:
list(zip([0,1,2], [1,2,3]))

[(0, 1), (1, 2), (2, 3)]

* Q2

In [151]:
[1, 2, 'a'].index('a')

2

In [141]:
L1 = [1, 2, 3]
L2 = [1, 2, 'a']
new = []
for i in L2:
    if i not in L1:
        new.append(i)
print(new)
print(L2.index(new[0]))

2

In [150]:
L1 = [1, 2, 3]
L2 = [1, 2, 'a']
new = []
for i in L2:
    try:
        L1.index(i)
    except:
        new.append(i)
        new.append(L2.index(i))
new

['a', 2]

* Q3

In [3]:
L1 = [1, 2, 3, 4, 5]
L2 = ['satr', 'moon']
L3 = [1, 2, 'star']
all_list = [L3, L2, L1]

# method 1
all_list_len = list(map(len, all_list))
print(all_list[all_list_len.index(max(all_list_len))])

# method 2
print(sorted(all_list, key = lambda x: len(x), reverse = True)[0])


[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]


## Jupyter Notebook

#### [1] 基本命令
* Esc + H
* Shift + Enter, Ctrl + Enter
* Esc + B, Esc + A
* Esc + Y, Esc + M, Esc + R
* Esc + L
* Esc + D + D, Esc + Z
* Shift + M

#### [2] 进阶操作
* Latex
* HTML
* Slides
* Magic 

#### APPENDIX
* Slides: `jupyter nbconvert notebook.ipynb --to slides --post serve`  
* Magic: `http://ipython.readthedocs.io/en/stable/interactive/magics.html`  
* Markdown: `https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet`
* `magic code + ?`  
* `
cd ..
import os
os.getcwd()
`
* `
%time
%%time
%timeit(fun(x))
`

In [19]:
%time list(map(lambda x: x**2, range(10)))

Wall time: 0 ns


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [35]:
def fun(*x):
    return map(lambda m: m**2, x)
#     return x**2

In [37]:
%timeit(fun(2, 3, 4, 5))

2.72 µs ± 887 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
new = []
for i in range(10):
    new.append(i**2)

## Python Programming


In [83]:
bin(ord('a'))

'0b1100001'

In [88]:
# 97
a = '1100001'
result = 0
for i, j in enumerate(a[::-1]):
    result += eval(j)*2**i
result

97

In [76]:
try:
    [1, 2].index(1)
    print(True)
except:
    print(False)
finally:
    print('Judge')

True
Judge


In [78]:
x = 3
'a = x'
print('a = {0}'.format(x))

a = 3


In [81]:
a = eval('3')
exec('b = 3')

#### [1] 基本数据类型与运算符
* int, float, bool, string, list, tuple, dict, set
* $+, -, \times, /, //, \%, x^2$
* $==, !=, >, <, >=, <=$
* $=, +=, -=, *=, /=, \%=, **=, //=$
* &, |, ^, ~, bin, ord  
`0^0=0; 0^1=1; 1^0=1; 1^1=0`  
`0|0=0; 0|1=1; 1|0=1; 1|1=1`  
* and, or, not
* in, not in
* is, is not
* print format, int(), type
* eval, exec

#### [2] Python语法
* if, filter
* for, map
* while
* try except finally
* zip, enumerate


In [87]:
# reduce(lambda x,y: x+y, list(range(4)))

In [91]:
x = [1, 2, 3, 4]
new = []
for i in x:
    if i > 3:
        new.append(i)

In [95]:
list(filter(lambda m: m if m > 3 else None, x))

[4]

In [97]:
a = 1
while a < 10:
    print(a)
    a += 1

1
2
3
4
5
6
7
8
9


In [110]:
for i,j in enumerate(range(1, 10)):
    print(i, j)

0 1
1 2
2 3
3 4
4 5
5 6
6 7
7 8
8 9


## Project: My Wechat Friends

In [ ]:
# other people
user = itchat.search_friends(name = u'name')[0]
user.send(u'test')

In [ ]:
# wordcloud
import PIL.Image as Image
alice_coloring = np.array(Image.open("wechat.jpg"))
my_wordcloud = WordCloud(background_color="white", max_words=2000, mask=alice_coloring,
                         max_font_size=40, random_state=42, font_path='./SimHei.ttf').generate(wl_space_split)
plt.figure(figsize = (12, 12))
plt.imshow(my_wordcloud)
plt.axis("off")
plt.show()
my_wordcloud.to_file(os.path.join("wechatfriends_wordcloud.png"))